services:
  web:
    build:
      context: ./web
      target: development
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
      - ./web/storage:/app/storage
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/app?schema=public
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-iL0MNW5R8dX1qZsjC4vP9aYb6Gk2HtUf}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-Qz7vL3mN8pR5sT2wX9yE4bH6kJ1cV0Za}
      ACCESS_TOKEN_EXPIRES_IN_MINUTES: ${ACCESS_TOKEN_EXPIRES_IN_MINUTES:-15}
      REFRESH_TOKEN_EXPIRES_IN_DAYS: ${REFRESH_TOKEN_EXPIRES_IN_DAYS:-7}
      NEXT_PUBLIC_APP_BASE_URL: http://localhost:3000
      ICON_STORAGE_DIR: /app/storage/icons
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  web_node_modules:
